using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SignalR102.Manager
{
    public class ContentHubManager
    {
        public string Content { get; set; }

        public Scroll Scroll { get; set; }


        public ContentHubManager()
        {
            Content = @"
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl pretium fusce id velit. Scelerisque felis imperdiet proin fermentum leo vel orci. Ac feugiat sed lectus vestibulum mattis. Ac odio tempor orci dapibus ultrices in. Dictum non consectetur a erat. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Pretium aenean pharetra magna ac. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Mattis aliquam faucibus purus in massa tempor. Hendrerit gravida rutrum quisque non tellus orci ac auctor augue. Ultrices sagittis orci a scelerisque purus semper eget duis. Sed elementum tempus egestas sed sed. Egestas erat imperdiet sed euismod nisi. Vitae elementum curabitur vitae nunc sed velit dignissim sodales. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc.

            Porta lorem mollis aliquam ut porttitor leo a. Nunc aliquet bibendum enim facilisis. Vitae auctor eu augue ut lectus arcu bibendum at varius. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Massa id neque aliquam vestibulum morbi blandit cursus. Imperdiet nulla malesuada pellentesque elit. Metus vulputate eu scelerisque felis imperdiet proin. Erat nam at lectus urna duis. Arcu risus quis varius quam quisque id diam. Eu scelerisque felis imperdiet proin fermentum leo vel orci porta. Ullamcorper velit sed ullamcorper morbi. Maecenas volutpat blandit aliquam etiam erat. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Felis donec et odio pellentesque diam volutpat. Elit ullamcorper dignissim cras tincidunt lobortis. Proin sagittis nisl rhoncus mattis rhoncus.

            Mi bibendum neque egestas congue. Lacus luctus accumsan tortor posuere. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Elit ullamcorper dignissim cras tincidunt. Nam at lectus urna duis convallis. Risus pretium quam vulputate dignissim suspendisse in est. Aliquet nibh praesent tristique magna sit amet purus. Viverra accumsan in nisl nisi scelerisque. Rhoncus dolor purus non enim praesent elementum facilisis leo. Habitasse platea dictumst quisque sagittis purus sit amet volutpat. Nunc lobortis mattis aliquam faucibus purus in. Dolor sit amet consectetur adipiscing elit ut.

            Volutpat commodo sed egestas egestas fringilla. Nibh nisl condimentum id venenatis a condimentum. Morbi quis commodo odio aenean sed adipiscing diam. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Amet consectetur adipiscing elit pellentesque. Facilisis volutpat est velit egestas dui id ornare arcu odio. Aliquet risus feugiat in ante metus. Tristique magna sit amet purus gravida quis blandit turpis. Pulvinar etiam non quam lacus suspendisse. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Proin sagittis nisl rhoncus mattis. Faucibus pulvinar elementum integer enim neque volutpat ac. Viverra nibh cras pulvinar mattis. In aliquam sem fringilla ut morbi tincidunt augue interdum velit. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent.

            Vestibulum lorem sed risus ultricies tristique. Leo a diam sollicitudin tempor id eu nisl nunc mi. Massa enim nec dui nunc. Tincidunt eget nullam non nisi est sit amet facilisis magna. Amet aliquam id diam maecenas ultricies. In massa tempor nec feugiat nisl pretium. Nisl nunc mi ipsum faucibus vitae aliquet. Ornare arcu dui vivamus arcu felis bibendum. Pharetra convallis posuere morbi leo urna molestie. Iaculis eu non diam phasellus vestibulum lorem sed risus ultricies. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Ultrices eros in cursus turpis massa tincidunt dui ut. Fermentum odio eu feugiat pretium nibh. Purus sit amet volutpat consequat mauris nunc congue. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Tincidunt augue interdum velit euismod in pellentesque. Nibh praesent tristique magna sit amet purus gravida quis blandit. Blandit turpis cursus in hac habitasse platea dictumst.

            In vitae turpis massa sed. Eu augue ut lectus arcu bibendum at. Tristique senectus et netus et malesuada fames ac turpis. Netus et malesuada fames ac turpis egestas sed tempus. Vulputate ut pharetra sit amet aliquam id. A cras semper auctor neque vitae tempus quam pellentesque nec. Fames ac turpis egestas maecenas pharetra convallis posuere morbi. Auctor urna nunc id cursus metus aliquam eleifend. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Tempor id eu nisl nunc mi ipsum faucibus vitae. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Morbi tempus iaculis urna id. Lorem ipsum dolor sit amet. Facilisis gravida neque convallis a cras semper auctor neque vitae.

            Nisl suscipit adipiscing bibendum est ultricies. Auctor augue mauris augue neque gravida in. Posuere urna nec tincidunt praesent semper feugiat nibh sed. Semper eget duis at tellus. Ut tortor pretium viverra suspendisse potenti nullam ac tortor. Tincidunt eget nullam non nisi est sit amet facilisis. Est sit amet facilisis magna etiam tempor orci eu lobortis. Iaculis urna id volutpat lacus laoreet non curabitur gravida. Venenatis cras sed felis eget. Semper auctor neque vitae tempus quam pellentesque nec. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Sit amet porttitor eget dolor morbi non arcu risus quis. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum.

            Risus in hendrerit gravida rutrum quisque non tellus orci. Leo integer malesuada nunc vel risus commodo viverra. Lobortis feugiat vivamus at augue eget arcu. Vehicula ipsum a arcu cursus. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Venenatis cras sed felis eget velit aliquet. Non sodales neque sodales ut etiam. Venenatis lectus magna fringilla urna porttitor. Nulla at volutpat diam ut. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Eget aliquet nibh praesent tristique magna. Purus gravida quis blandit turpis cursus in hac habitasse platea. Commodo nulla facilisi nullam vehicula ipsum a arcu. Pharetra magna ac placerat vestibulum. In aliquam sem fringilla ut morbi tincidunt augue interdum velit. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et netus. Viverra nam libero justo laoreet sit amet cursus sit. Enim facilisis gravida neque convallis a cras. Tempor id eu nisl nunc mi ipsum faucibus vitae. Pharetra magna ac placerat vestibulum.

            Odio ut sem nulla pharetra diam sit amet nisl. Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Pharetra sit amet aliquam id. Ut lectus arcu bibendum at varius vel. Hac habitasse platea dictumst quisque sagittis. Varius vel pharetra vel turpis nunc eget lorem. Vitae purus faucibus ornare suspendisse sed nisi. Ante in nibh mauris cursus mattis molestie. Mattis aliquam faucibus purus in massa tempor nec. Nec tincidunt praesent semper feugiat nibh sed. Vulputate ut pharetra sit amet aliquam id diam maecenas ultricies. Non arcu risus quis varius quam quisque id diam. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Tincidunt praesent semper feugiat nibh sed. Auctor augue mauris augue neque gravida in fermentum. Pellentesque adipiscing commodo elit at imperdiet. Cursus eget nunc scelerisque viverra mauris in aliquam sem.

            Viverra nam libero justo laoreet sit amet. Id venenatis a condimentum vitae sapien pellentesque. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Duis convallis convallis tellus id. Tincidunt arcu non sodales neque sodales ut etiam sit amet. Gravida in fermentum et sollicitudin ac orci phasellus egestas. Nibh mauris cursus mattis molestie a iaculis at. Nec tincidunt praesent semper feugiat. Faucibus a pellentesque sit amet porttitor eget dolor morbi non. Eget nulla facilisi etiam dignissim diam. Erat pellentesque adipiscing commodo elit at imperdiet. Interdum consectetur libero id faucibus nisl tincidunt. Amet nisl purus in mollis nunc sed.

            At augue eget arcu dictum varius duis. Consequat id porta nibh venenatis cras sed felis eget velit. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Fames ac turpis egestas maecenas pharetra convallis posuere morbi leo. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Iaculis urna id volutpat lacus laoreet non curabitur. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Id porta nibh venenatis cras sed felis eget. Eget sit amet tellus cras. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Pulvinar mattis nunc sed blandit libero volutpat sed cras ornare. Volutpat consequat mauris nunc congue nisi vitae. At auctor urna nunc id cursus metus aliquam eleifend mi.

            Quam viverra orci sagittis eu volutpat odio. Egestas purus viverra accumsan in nisl. Dignissim enim sit amet venenatis urna. Id diam maecenas ultricies mi eget mauris. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Tortor vitae purus faucibus ornare suspendisse sed nisi. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Auctor augue mauris augue neque gravida in fermentum. Tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum. Aliquet bibendum enim facilisis gravida neque convallis. Massa ultricies mi quis hendrerit dolor magna. Cum sociis natoque penatibus et magnis dis parturient montes.

            Posuere ac ut consequat semper viverra nam libero justo laoreet. Fames ac turpis egestas maecenas pharetra convallis. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Tincidunt lobortis feugiat vivamus at augue eget arcu. Eu augue ut lectus arcu. Sit amet aliquam id diam maecenas ultricies mi eget. Blandit aliquam etiam erat velit. Velit dignissim sodales ut eu sem integer vitae. Vitae congue mauris rhoncus aenean vel elit scelerisque. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Aliquam ut porttitor leo a diam. Gravida quis blandit turpis cursus. Eget gravida cum sociis natoque. Tortor at risus viverra adipiscing at in tellus. Vestibulum lectus mauris ultrices eros in cursus turpis. Ullamcorper sit amet risus nullam. Tortor at auctor urna nunc id cursus metus aliquam eleifend. At auctor urna nunc id cursus metus aliquam eleifend. Viverra justo nec ultrices dui sapien eget mi proin sed.

            Sem et tortor consequat id porta nibh. Semper viverra nam libero justo. Commodo sed egestas egestas fringilla. Cras ornare arcu dui vivamus arcu felis. Sit amet dictum sit amet justo. Tristique nulla aliquet enim tortor. Volutpat maecenas volutpat blandit aliquam etiam erat. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Amet mauris commodo quis imperdiet. Vel pharetra vel turpis nunc eget lorem dolor. Ultrices vitae auctor eu augue. Massa enim nec dui nunc mattis. Maecenas accumsan lacus vel facilisis volutpat. Felis bibendum ut tristique et. Elementum integer enim neque volutpat ac tincidunt vitae semper quis. Purus in massa tempor nec feugiat nisl pretium fusce. Massa massa ultricies mi quis hendrerit dolor magna. Tellus id interdum velit laoreet id donec ultrices.

            Pulvinar elementum integer enim neque volutpat ac. Massa tempor nec feugiat nisl pretium. Non enim praesent elementum facilisis. Penatibus et magnis dis parturient. Tristique senectus et netus et malesuada. Quis imperdiet massa tincidunt nunc. Aliquet bibendum enim facilisis gravida neque convallis a. At tempor commodo ullamcorper a lacus vestibulum sed arcu. Suscipit adipiscing bibendum est ultricies integer quis auctor elit. Mauris sit amet massa vitae tortor condimentum lacinia.

            Leo vel fringilla est ullamcorper. Suspendisse sed nisi lacus sed. Id aliquet lectus proin nibh nisl condimentum. Risus nec feugiat in fermentum posuere urna nec tincidunt. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Aliquet bibendum enim facilisis gravida neque convallis a. Blandit cursus risus at ultrices. Viverra justo nec ultrices dui sapien eget mi proin sed. Nec nam aliquam sem et tortor consequat id. Metus aliquam eleifend mi in nulla posuere sollicitudin. Ullamcorper sit amet risus nullam eget felis.

            Dui vivamus arcu felis bibendum ut tristique. Ullamcorper sit amet risus nullam eget felis eget. Egestas dui id ornare arcu odio. Arcu ac tortor dignissim convallis aenean. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Nisi quis eleifend quam adipiscing. A iaculis at erat pellentesque adipiscing. Suspendisse ultrices gravida dictum fusce. Et netus et malesuada fames ac turpis egestas integer eget. Sapien et ligula ullamcorper malesuada proin libero nunc consequat interdum. Donec ac odio tempor orci dapibus ultrices in. Auctor urna nunc id cursus metus aliquam. Volutpat consequat mauris nunc congue nisi. Fames ac turpis egestas integer. Non consectetur a erat nam at lectus urna duis convallis. Morbi tincidunt augue interdum velit euismod in. Ultricies tristique nulla aliquet enim tortor. Purus viverra accumsan in nisl nisi scelerisque. Odio ut enim blandit volutpat maecenas volutpat. Volutpat commodo sed egestas egestas fringilla phasellus faucibus.

            Integer enim neque volutpat ac tincidunt vitae. Porta nibh venenatis cras sed. Convallis aenean et tortor at risus viverra adipiscing. Placerat vestibulum lectus mauris ultrices eros. Viverra orci sagittis eu volutpat odio facilisis. In dictum non consectetur a erat. Et pharetra pharetra massa massa ultricies mi. Aliquam faucibus purus in massa tempor nec. Tellus id interdum velit laoreet. Sit amet justo donec enim. In massa tempor nec feugiat nisl pretium. Et egestas quis ipsum suspendisse ultrices gravida dictum. Eget mi proin sed libero enim sed. Quam elementum pulvinar etiam non. Et malesuada fames ac turpis egestas maecenas. Morbi tincidunt ornare massa eget. Tortor posuere ac ut consequat semper viverra. Accumsan in nisl nisi scelerisque eu ultrices vitae. Fermentum iaculis eu non diam phasellus vestibulum lorem sed risus. Neque aliquam vestibulum morbi blandit cursus risus at.

            Ultricies lacus sed turpis tincidunt id aliquet. Quis blandit turpis cursus in hac habitasse platea dictumst. Id leo in vitae turpis. Auctor urna nunc id cursus metus aliquam. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Varius sit amet mattis vulputate enim nulla aliquet. Magna etiam tempor orci eu lobortis elementum nibh. Neque convallis a cras semper auctor neque vitae. Sodales ut eu sem integer vitae justo. A cras semper auctor neque vitae. Maecenas sed enim ut sem. Dignissim enim sit amet venenatis urna cursus eget nunc. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Sit amet venenatis urna cursus eget nunc. Mauris vitae ultricies leo integer malesuada nunc vel risus commodo. Elementum facilisis leo vel fringilla est ullamcorper eget.

            Adipiscing commodo elit at imperdiet dui accumsan sit. Odio tempor orci dapibus ultrices in iaculis. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Neque sodales ut etiam sit. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. A scelerisque purus semper eget duis. Nec dui nunc mattis enim ut tellus. In dictum non consectetur a. Tempor commodo ullamcorper a lacus. Viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Mi proin sed libero enim sed faucibus turpis. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Eget nunc scelerisque viverra mauris in aliquam sem fringilla.

            Dictum varius duis at consectetur lorem donec massa sapien faucibus. Interdum velit euismod in pellentesque massa placerat. Curabitur vitae nunc sed velit dignissim. Diam sollicitudin tempor id eu nisl. Rhoncus urna neque viverra justo nec ultrices. Tincidunt eget nullam non nisi est. Commodo elit at imperdiet dui accumsan sit amet. Congue quisque egestas diam in arcu cursus euismod. Aliquet porttitor lacus luctus accumsan. Purus non enim praesent elementum facilisis leo. Urna condimentum mattis pellentesque id nibh tortor id.

            Pharetra sit amet aliquam id. Sed euismod nisi porta lorem mollis aliquam ut porttitor. Viverra tellus in hac habitasse platea. Ut ornare lectus sit amet est. Integer feugiat scelerisque varius morbi enim nunc faucibus. Libero id faucibus nisl tincidunt eget. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. Faucibus purus in massa tempor. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Ornare suspendisse sed nisi lacus.

            Augue ut lectus arcu bibendum at varius vel pharetra vel. Rhoncus mattis rhoncus urna neque viverra justo nec. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. Mus mauris vitae ultricies leo integer malesuada. Eu sem integer vitae justo eget magna fermentum. Suspendisse sed nisi lacus sed viverra tellus in. Interdum posuere lorem ipsum dolor sit amet consectetur. In ornare quam viverra orci sagittis eu volutpat. Adipiscing bibendum est ultricies integer quis auctor. Quisque sagittis purus sit amet volutpat consequat mauris. Volutpat blandit aliquam etiam erat velit scelerisque. Quam lacus suspendisse faucibus interdum posuere lorem.

            Elementum integer enim neque volutpat ac tincidunt vitae semper quis. Quam adipiscing vitae proin sagittis nisl. Tincidunt vitae semper quis lectus nulla at. Mollis nunc sed id semper risus in. Enim praesent elementum facilisis leo vel fringilla est ullamcorper. Egestas congue quisque egestas diam in arcu. Bibendum at varius vel pharetra vel turpis nunc eget lorem. Sagittis orci a scelerisque purus semper eget. Dictum sit amet justo donec enim diam vulputate ut pharetra. Odio ut enim blandit volutpat maecenas volutpat. Arcu cursus euismod quis viverra. Volutpat blandit aliquam etiam erat. Diam quis enim lobortis scelerisque fermentum dui. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Commodo ullamcorper a lacus vestibulum sed arcu non odio euismod. Morbi leo urna molestie at elementum eu facilisis sed odio. Ac auctor augue mauris augue neque gravida. Sit amet dictum sit amet justo. Lorem ipsum dolor sit amet. Feugiat pretium nibh ipsum consequat nisl vel pretium.

            Est lorem ipsum dolor sit amet consectetur. Nisl purus in mollis nunc. At tempor commodo ullamcorper a lacus. Euismod in pellentesque massa placerat duis ultricies. Nibh venenatis cras sed felis eget velit. Turpis egestas integer eget aliquet nibh. Felis bibendum ut tristique et egestas quis. Eget nullam non nisi est sit amet facilisis magna etiam. In metus vulputate eu scelerisque. Sit amet nisl purus in mollis nunc sed. Tortor aliquam nulla facilisi cras fermentum odio eu. Eget nullam non nisi est sit amet facilisis magna etiam. Neque egestas congue quisque egestas diam. Sit amet consectetur adipiscing elit duis tristique. Ut sem nulla pharetra diam sit amet nisl suscipit adipiscing. Dignissim sodales ut eu sem integer. Donec pretium vulputate sapien nec sagittis aliquam. Adipiscing enim eu turpis egestas pretium aenean. Vitae tortor condimentum lacinia quis vel eros donec ac. Fringilla urna porttitor rhoncus dolor purus.

            Viverra nibh cras pulvinar mattis nunc sed. Risus in hendrerit gravida rutrum. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Diam ut venenatis tellus in metus vulputate. Iaculis nunc sed augue lacus viverra vitae congue eu. Viverra vitae congue eu consequat. Massa placerat duis ultricies lacus sed turpis tincidunt id. Vestibulum morbi blandit cursus risus at ultrices. Erat pellentesque adipiscing commodo elit at. Rhoncus urna neque viverra justo nec ultrices dui. Ullamcorper malesuada proin libero nunc consequat. Malesuada proin libero nunc consequat interdum. A erat nam at lectus urna. Senectus et netus et malesuada fames. Velit sed ullamcorper morbi tincidunt ornare massa. Nunc non blandit massa enim nec dui nunc. Viverra suspendisse potenti nullam ac. Bibendum est ultricies integer quis auctor.

            Feugiat nisl pretium fusce id velit. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Quam vulputate dignissim suspendisse in est ante in nibh. Volutpat ac tincidunt vitae semper quis lectus nulla. Amet consectetur adipiscing elit pellentesque habitant morbi tristique. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Velit scelerisque in dictum non consectetur. Vestibulum sed arcu non odio euismod lacinia. Fames ac turpis egestas sed tempus urna et. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant.

            Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Morbi enim nunc faucibus a pellentesque. Lacus suspendisse faucibus interdum posuere. Amet commodo nulla facilisi nullam vehicula ipsum a. Magna fringilla urna porttitor rhoncus dolor. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt vitae. Ac tortor vitae purus faucibus ornare suspendisse. Mi sit amet mauris commodo quis imperdiet massa tincidunt nunc. Vestibulum rhoncus est pellentesque elit ullamcorper. Ultrices neque ornare aenean euismod elementum nisi quis eleifend quam. Arcu bibendum at varius vel pharetra. Tempor id eu nisl nunc mi. Aliquet lectus proin nibh nisl condimentum id venenatis. Elit ut aliquam purus sit. Pretium viverra suspendisse potenti nullam. Enim ut tellus elementum sagittis vitae. Eu ultrices vitae auctor eu augue ut lectus. In nisl nisi scelerisque eu. Elit sed vulputate mi sit amet mauris commodo.

            Netus et malesuada fames ac turpis egestas. Facilisis sed odio morbi quis. Nisi est sit amet facilisis magna etiam tempor. Mattis pellentesque id nibh tortor. Amet purus gravida quis blandit turpis cursus in hac habitasse. Aliquet lectus proin nibh nisl condimentum id. Dui id ornare arcu odio ut sem nulla. Ut morbi tincidunt augue interdum. Lectus sit amet est placerat in. Ultrices eros in cursus turpis massa tincidunt dui ut ornare. Elit scelerisque mauris pellentesque pulvinar. Imperdiet massa tincidunt nunc pulvinar. Enim diam vulputate ut pharetra sit amet aliquam. Posuere lorem ipsum dolor sit amet.

            Metus vulputate eu scelerisque felis imperdiet. Urna porttitor rhoncus dolor purus non enim praesent. Dignissim sodales ut eu sem integer. Diam maecenas ultricies mi eget mauris pharetra et. Scelerisque eleifend donec pretium vulputate sapien nec. Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Iaculis eu non diam phasellus. Placerat in egestas erat imperdiet sed euismod. Amet venenatis urna cursus eget nunc. Facilisi etiam dignissim diam quis. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Mattis aliquam faucibus purus in massa tempor nec. Purus semper eget duis at. At quis risus sed vulputate odio ut enim.";
            Scroll = new Scroll();
            Scroll.X = 0;
            Scroll.Y = 0;
        }
    }
    public class Scroll
    {
        public int X { get; set; }
        public int Y { get; set; }
    }
}

